### ISSUE TITLE
[Discussion] 引用传递引起的数据污染问题讨论

### ISSUE THREAD

**Issue by cryzzchen** [raxjs/pwc#50]
# 问题描述

在 Javascript 语言中，复杂类型（Array, Function, Object 等）的数据是通过引用传递的。这意味着，任何一处修改，都会直接改变这个数据本身，从而影响其他使用该数据的函数。

这个特性有时是我们需要的，有时又是我们想极力避免的。

在 Web Components 中，我们可以通过修改组件的 property 来传递属性。当 property 类型为复杂类型时，就会产生上面的问题。

名词说明：以下出现 Web Components 时，均表示 PWC 增强后。

# 避免引用传递

React, Vue 框架采用这个方案。

这个方案在实现时，通常有两种思路，也可以两种思路相结合：
- 父子组件传递属性时，子组件使用的实际上是父组件数据的拷贝，而不是其本身；
- 组件的接收的外部属性的值被 `freeze`，从而确保组件不会修改外部数据；

在标准中，每个组件会声明可以接收的属性，这些属性本身表明了组件的自身状态，外部可以修改这些属性值来达到传参的目的。以 checkbox 为例，组件本身在被点击后，会改变属性 `checked` 的值，外部也可以修改组件实例的 `checked` 来改变组件。

因此在 PWC 中，不能使用 `freeze`，而是单独使用拷贝的方式来达到避免引用传递的目的。

![image](https://user-images.githubusercontent.com/3948124/163746112-a57ef8cd-ea80-4213-8c8b-191948c91ccf.png)

避免引用传递有两个方案。
## 方案一

在传递数据前，对数据做拷贝处理，即在 Web Components 中所有需要传递给其他组件的数据都做拷贝后，再传递给其他组件：
好处：所有 Web Components 中的数据都是安全的，不会被子组件修改；
坏处：若外部环境不是 Web Components 时，可能会污染外部环境的数据；存在不必要的性能损耗；

## 方案二

在使用数据前，先对数据做拷贝处理：
好处：无论外部环境是不是 Web Components，都能避免污染外部环境的数据；
坏处：实现该功能有赖于 `accessor` 访问器，因此只有添加 `reactive` 装饰器的属性才能做拷贝处理；

# 引用传递

## 方案三
不做特殊处理，维持 Javascript 语言的引用传递特性。

Lit, stenciljs 框架采用这个方案。其中 stenciljs 由于规定了只有[直接给属性赋值](https://stenciljs.com/docs/reactive-data#handling-arrays-and-objects)时才能触发更新，可以避免用户因修改父组件数据造成数据污染的问题。

# 方案对比

|  | 优点 | 缺点 |
| ------ | --- | ------ |
| 方案一 | 避免数据污染 | 当 Web Components 与其他框架混用或 JS 直接修改组件属性时，行为存在不一致问题 |
| 方案二 |  避免数据污染 | 依赖装饰器 |
| 方案三 | 与 Javascript 语言特性保持一致 | 无论是组件的属性还是使用的外部数据都可能被污染 |

方案二可以被看做在方案三的基础上提供了一个默认 shallowClone 的方式。

**Comment by SoloJiang** [comment]
方案一和方案二其实需要关注的点是，是不是大多数开发者都希望是数据安全的

**Comment by cryzzchen** [comment]
选择方案二：在保持 Javascript 语言特性的基础上，提供一个默认限制数据污染的方案。
